name: kde-plasma
version: 5.21.1
repo: core
deps: [
  'lxdm',
  'xf86-video-fbdev',
  'xf86-video-intel',
  'xf86-video-nouveau',
  'kdecoration',
  'libkscreen',
  'libksysguard',
  'breeze',
  'breeze-gtk',
  'kscreenlocker',
  'oxygen',
  'kinfocenter',
  'ksysguard',
  'kwayland-server',
  'kwin',
  'plasma-workspace',
  'plasma-disks',
  'bluedevil',
  'kde-gtk-config',
  'khotkeys',
  'kmenuedit',
  'kscreen',
  'kwallet-pam',
  'kwayland-integration',
  'kwrited',
  'milou',
  'plasma-nm',
  'plasma-pa',
  'plasma-workspace-wallpapers',
  'polkit-kde-agent-1',
  'powerdevil',
  'plasma-desktop',
  'kdeplasma-addons',
  'kgamma5',
  'ksshaskpass',
  'sddm-kcm',
  'discover',
  'kactivitymanagerd',
  'plasma-integration',
  'plasma-tests',
  'xdg-desktop-portal-kde',
  'drkonqi',
  'plasma-vault',
  'plasma-browser-integration',
  'kde-cli-tools',
  'systemsettings',
  'plasma-thunderbolt',
  'plasma-firewall',
  'plasma-systemmonitor',
  'qqc2-breeze-style',
]
mkdeps: []
extras: [
]
