#!/usr/bin/env python3

import json
import os
import subprocess
import sys
from os import path
import tempfile
from subprocess import Popen, PIPE, DEVNULL
import shutil
import plx

if len(sys.argv) < 2:
    print("Usage: buildpck <package_name>")
    sys.exit(1)

pck = sys.argv[1]

plx.build_package(pck)

print("")
print("DONE")
print("")
