#!/usr/bin/env python3

import urllib.request
from tqdm import tqdm
import sys

class DownloadProgressBar(tqdm):
    def update_to(self, b=1, bsize=1, tsize=None):
        if tsize is not None:
            self.total = tsize
        self.update(b * bsize - self.n)


def download_url(url, output_path):
    with DownloadProgressBar(unit='B', unit_scale=True,
                             miniters=1, desc=url.split('/')[-1]) as t:
        urllib.request.urlretrieve(url, filename=output_path, reporthook=t.update_to)

if len(sys.argv) < 3:
    print("Usage: plx-get <url> <output_path>")
    sys.exit(1)

url = sys.argv[1]
download_url(url, sys.argv[2])
