#!/usr/bin/env python3

import sys

from plx import download_pck_info

if len(sys.argv) < 3:
    print("Usage: plx-getpck <package_name> <download_path>")
    sys.exit(1)

nobuild = False

if len(sys.argv) > 3 and sys.argv[3] == "nobuild":
    nobuild = True

download_pck_info(sys.argv[1], sys.argv[2], nobuild)
