#!/usr/bin/env python3

from plx import download_url
import sys

if len(sys.argv) < 3:
    print("Usage: plx-get <url> <output_path>")
    sys.exit(1)

url = sys.argv[1]
download_url(url, sys.argv[2])
